{"context": "\u305f\u307e\u306b\u3057\u304b\u30b3\u30fc\u30c7\u30a3\u30f3\u30b0\u3057\u306a\u3044\u3068\u3059\u3050\u306b\u5fd8\u308c\u3061\u3083\u3046\u3002\nPython \u306e\u95a2\u6570\u5b9a\u7fa9\u3067\u5f15\u6570\u306b * (\u30a2\u30b9\u30bf\u30ea\u30b9\u30af)\u304c1\u500b\u3060\u3051\u6307\u5b9a\u3055\u308c\u3066\u3044\u308b\u3068\u304d\u304c\u3042\u308b(\u6a19\u6e96\u30e9\u30a4\u30d6\u30e9\u30ea\u306e\u30bd\u30fc\u30b9\u3068\u304b\u898b\u3066\u308b\u3068\u3061\u3087\u3044\u3061\u3087\u3044\u3042\u308b):\ndef connect_accepted_socket(self, protocol_factory, sock, *, ssl=None):\n\u3053\u308c\u306f\u3001\n\n\u201c*\u201d \u3084 \u201c*identifier\u201d \u306e\u5f8c\u306e\u5f15\u6570\u306f\u30ad\u30fc\u30ef\u30fc\u30c9\u5c02\u7528\u5f15\u6570\u3067\u3001\u30ad\u30fc\u30ef\u30fc\u30c9\u5f15\u6570\u3092\u4f7f\u3063\u3066\u306e\u307f\u6e21\u3055\u308c\u307e\u3059\u3002\n\nhttp://docs.python.jp/3/reference/compound_stmts.html#function-definitions\n\u3059\u306a\u308f\u3061 *, \u3092\u306f\u3055\u3080\u3068\u3001\u305d\u308c\u3088\u308a\u3042\u3068\u306e\u5f15\u6570\u306f\u300c\u30ad\u30fc\u30ef\u30fc\u30c9\u5f15\u6570\u3068\u3057\u3066\u3067\u306a\u3044\u3068\u53d7\u3051\u4ed8\u3051\u306a\u3044\u300d(\u4f4d\u7f6e\u5f15\u6570\u3067\u306f\u53d7\u3051\u4ed8\u3051\u306a\u3044)\u3068\u3044\u3046\u3053\u3068\u3002\n>>> def test(a, b, *, c=False):\n...     print(a if c else b)\n... \n>>> test(1, 2)\n2\n>>> test(1, 2, c=True)\n1\n>>> test(1, 2, True)\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nTypeError: test() takes 2 positional arguments but 3 were given\n\n\u300c\u30a2\u30b9\u30bf\u30ea\u30b9\u30af\u300d\u3068\u3044\u3061\u3044\u3061\u66f8\u304f\u306e\u306f\u691c\u7d22\u7528\u3002\n\u81ea\u5206\u81ea\u8eab\u304c\u3053\u306e\u6295\u7a3f\u3092\u3057\u305f\u4e8b\u5b9f\u3092\u5fd8\u308c\u3066\u3057\u307e\u3063\u305f\u3068\u304d\u306e\u305f\u3081\u306b\u3002\n\u305f\u307e\u306b\u3057\u304b\u30b3\u30fc\u30c7\u30a3\u30f3\u30b0\u3057\u306a\u3044\u3068\u3059\u3050\u306b\u5fd8\u308c\u3061\u3083\u3046\u3002\n\nPython \u306e\u95a2\u6570\u5b9a\u7fa9\u3067\u5f15\u6570\u306b * (\u30a2\u30b9\u30bf\u30ea\u30b9\u30af)\u304c1\u500b\u3060\u3051\u6307\u5b9a\u3055\u308c\u3066\u3044\u308b\u3068\u304d\u304c\u3042\u308b(\u6a19\u6e96\u30e9\u30a4\u30d6\u30e9\u30ea\u306e\u30bd\u30fc\u30b9\u3068\u304b\u898b\u3066\u308b\u3068\u3061\u3087\u3044\u3061\u3087\u3044\u3042\u308b):\n\n`def connect_accepted_socket(self, protocol_factory, sock, *, ssl=None):`\n\n\u3053\u308c\u306f\u3001\n\n> \u201c*\u201d \u3084 \u201c*identifier\u201d \u306e\u5f8c\u306e\u5f15\u6570\u306f\u30ad\u30fc\u30ef\u30fc\u30c9\u5c02\u7528\u5f15\u6570\u3067\u3001\u30ad\u30fc\u30ef\u30fc\u30c9\u5f15\u6570\u3092\u4f7f\u3063\u3066\u306e\u307f\u6e21\u3055\u308c\u307e\u3059\u3002\n\nhttp://docs.python.jp/3/reference/compound_stmts.html#function-definitions\n\n\u3059\u306a\u308f\u3061 `*,` \u3092\u306f\u3055\u3080\u3068\u3001\u305d\u308c\u3088\u308a\u3042\u3068\u306e\u5f15\u6570\u306f\u300c\u30ad\u30fc\u30ef\u30fc\u30c9\u5f15\u6570\u3068\u3057\u3066\u3067\u306a\u3044\u3068\u53d7\u3051\u4ed8\u3051\u306a\u3044\u300d(\u4f4d\u7f6e\u5f15\u6570\u3067\u306f\u53d7\u3051\u4ed8\u3051\u306a\u3044)\u3068\u3044\u3046\u3053\u3068\u3002\n\n```python\n>>> def test(a, b, *, c=False):\n...     print(a if c else b)\n... \n>>> test(1, 2)\n2\n>>> test(1, 2, c=True)\n1\n>>> test(1, 2, True)\nTraceback (most recent call last):\n  File \"<stdin>\", line 1, in <module>\nTypeError: test() takes 2 positional arguments but 3 were given\n```\n\n\u300c\u30a2\u30b9\u30bf\u30ea\u30b9\u30af\u300d\u3068\u3044\u3061\u3044\u3061\u66f8\u304f\u306e\u306f\u691c\u7d22\u7528\u3002\n\u81ea\u5206\u81ea\u8eab\u304c\u3053\u306e\u6295\u7a3f\u3092\u3057\u305f\u4e8b\u5b9f\u3092\u5fd8\u308c\u3066\u3057\u307e\u3063\u305f\u3068\u304d\u306e\u305f\u3081\u306b\u3002\n", "tags": ["Python", "\u5099\u5fd8\u9332"]}