{"tags": ["Python", "dlib", "OpenCV3"], "context": "\n\n\u4eca\u65e5\u306e\u76ee\u6a19\n\nOpenCV + dlib\u3067\u9854\u8a8d\u8b58\u306a\u3069\n\n\u524d\u56de\u307e\u3067\u306e\u307e\u3068\u3081\n\nconda\u306eOpenCV\u306b\u306fffmpeg\u304c\u5165\u3063\u3066\u3044\u306a\u3044 -> \u81ea\u524d\u30d3\u30eb\u30c9\u3067\u89e3\u6c7a\n\u203bcmake\u304c\u4e0a\u624b\u304f\u52d5\u304b\u306a\u3044\u306e\u3067opencvfindpython.cmake\u306e\u4e2d\u306e\u8a18\u8ff0\u3092python2\u512a\u5148\u90e8\u5206\u3092python3\u512a\u5148\u306b\u66f8\u304d\u63db\u3048\u3001\u30d3\u30eb\u30c9\uff06\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306b\u6210\u529f\n\u203bOpenCV\u306ecmake\u304cpyenv\u5185\u306epython\u30d0\u30fc\u30b8\u30e7\u30f3(PythonInterp)\u3092\u4e0a\u624b\u304f\u8a8d\u8b58\u3057\u306a\u3044\u554f\u984c\u306b\u3064\u3044\u3066\u306f\u672a\u89e3\u6c7a\n\n\n\u4eca\u65e5\u306e\u9032\u6357\n\n\npip dlib\u304clibpng.so.16\u304c\u7121\u3044\u3068\u6012\u308b\n->dlib\u3092\u30de\u30cb\u30e5\u30a2\u30eb\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n\n$ python setup.py install\n\n/usr/bin/ld: ~/.pyenv/versions/3.5.2/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC\n~/.pyenv/versions/3.5.2/lib/libpython3.5m.a: error adding symbols: Bad value\ncollect2: error: ld returned 1 exit status\nCMakeFiles/dlib_.dir/build.make:528: recipe for target 'dlib.so' failed\nmake[2]: *** [dlib.so] Error 1\nCMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_.dir/all' failed\nmake[1]: *** [CMakeFiles/dlib_.dir/all] Error 2\nMakefile:127: recipe for target 'all' failed\nmake: *** [all] Error 2\nerror: cmake build failed!\n\n\n\u4ee5\u4e0b\u3067\u89e3\u6c7a\n\n$ CFLAGS=\"-fPIC\" CONFIGURE_OPT=\"--enable-shared\" pyenv install 3.5.2\n$ python setup.py install\n\n\n\u4eca\u65e5\u306e\u8ab2\u984c\u89e3\u6c7a\u306f\u4ee5\u4e0b\u306e\u901a\u308a\n\nimport cv2, dlib\nimport matplotlib.pyplot as plt\nimport matplotlib.patches as patches\nimport matplotlib.animation as animation\n\nVIDEO_PATH = '~/video/video_20170123_161533.mp4'\n\ndetector = dlib.get_frontal_face_detector()\nvideo_capture = cv2.VideoCapture(VIDEO_PATH)\n\ndef face_detect(img):\n    rects, _, _ = detector.run(image=img, upsample_num_times=1)\n    if len(rects)>0:\n        rect = rects[0]\n        return rect\n\ndef plot(frame):\n    if video_capture.isOpened():\n        plt.cla()\n        ret, img = video_capture.read()\n        rect = face_detect(img)\n        plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))\n        patch = patches.Rectangle((rect.left(),rect.top()),rect.width(),rect.height(),linewidth=1,edgecolor='r',facecolor='none')\n        plt.gca().add_patch(patch)\n\nfig,ax = plt.subplots(1)\nani = animation.FuncAnimation(fig,plot)\n\n# \u4eca\u65e5\u306e\u76ee\u6a19\n## OpenCV + dlib\u3067\u9854\u8a8d\u8b58\u306a\u3069\n### \u524d\u56de\u307e\u3067\u306e\u307e\u3068\u3081\n- conda\u306eOpenCV\u306b\u306fffmpeg\u304c\u5165\u3063\u3066\u3044\u306a\u3044 -> \u81ea\u524d\u30d3\u30eb\u30c9\u3067\u89e3\u6c7a  \n\u203bcmake\u304c\u4e0a\u624b\u304f\u52d5\u304b\u306a\u3044\u306e\u3067opencvfindpython.cmake\u306e\u4e2d\u306e\u8a18\u8ff0\u3092python2\u512a\u5148\u90e8\u5206\u3092python3\u512a\u5148\u306b\u66f8\u304d\u63db\u3048\u3001\u30d3\u30eb\u30c9\uff06\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306b\u6210\u529f  \n\u203bOpenCV\u306ecmake\u304cpyenv\u5185\u306epython\u30d0\u30fc\u30b8\u30e7\u30f3(PythonInterp)\u3092\u4e0a\u624b\u304f\u8a8d\u8b58\u3057\u306a\u3044\u554f\u984c\u306b\u3064\u3044\u3066\u306f\u672a\u89e3\u6c7a\n\n### \u4eca\u65e5\u306e\u9032\u6357\n- ```pip dlib```\u304clibpng.so.16\u304c\u7121\u3044\u3068\u6012\u308b  \n->dlib\u3092\u30de\u30cb\u30e5\u30a2\u30eb\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n\n```\n$ python setup.py install\n\n/usr/bin/ld: ~/.pyenv/versions/3.5.2/lib/libpython3.5m.a(abstract.o): relocation R_X86_64_32S against `_Py_NotImplementedStruct' can not be used when making a shared object; recompile with -fPIC\n~/.pyenv/versions/3.5.2/lib/libpython3.5m.a: error adding symbols: Bad value\ncollect2: error: ld returned 1 exit status\nCMakeFiles/dlib_.dir/build.make:528: recipe for target 'dlib.so' failed\nmake[2]: *** [dlib.so] Error 1\nCMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/dlib_.dir/all' failed\nmake[1]: *** [CMakeFiles/dlib_.dir/all] Error 2\nMakefile:127: recipe for target 'all' failed\nmake: *** [all] Error 2\nerror: cmake build failed!\n``` \n\n- \u4ee5\u4e0b\u3067\u89e3\u6c7a\n\n```\n$ CFLAGS=\"-fPIC\" CONFIGURE_OPT=\"--enable-shared\" pyenv install 3.5.2\n$ python setup.py install\n```\n\n- \u4eca\u65e5\u306e\u8ab2\u984c\u89e3\u6c7a\u306f\u4ee5\u4e0b\u306e\u901a\u308a\n\n```\nimport cv2, dlib\nimport matplotlib.pyplot as plt\nimport matplotlib.patches as patches\nimport matplotlib.animation as animation\n\nVIDEO_PATH = '~/video/video_20170123_161533.mp4'\n\ndetector = dlib.get_frontal_face_detector()\nvideo_capture = cv2.VideoCapture(VIDEO_PATH)\n\ndef face_detect(img):\n    rects, _, _ = detector.run(image=img, upsample_num_times=1)\n    if len(rects)>0:\n        rect = rects[0]\n        return rect\n\ndef plot(frame):\n    if video_capture.isOpened():\n        plt.cla()\n        ret, img = video_capture.read()\n        rect = face_detect(img)\n        plt.imshow(cv2.cvtColor(img,cv2.COLOR_BGR2RGB))\n        patch = patches.Rectangle((rect.left(),rect.top()),rect.width(),rect.height(),linewidth=1,edgecolor='r',facecolor='none')\n        plt.gca().add_patch(patch)\n\nfig,ax = plt.subplots(1)\nani = animation.FuncAnimation(fig,plot)\n```\n"}