{"context": "\u4e00\u4eba\u3067\u304a\u52c9\u5f37\u3059\u308b\u306b\u3082\u76ee\u6a19\u306a\u304f\u3084\u3063\u3066\u3044\u308b\u3068\u8272\u3093\u306a\u8a98\u60d1\u306b\u8ca0\u3051\u305d\u3046\u306b\u306a\u308b\u306e\u3067\n\u5b50\u4f9b\u306e\u3054\u8912\u7f8e\u30b7\u30fc\u30eb\u3068\u3044\u3046\u7a0b\u306e\u3082\u306e\u3067\u3082\u306a\u3044\u3051\u3069\u5de5\u7a0b\u7ba1\u7406\u3067\u9054\u6210\u611f\u3092\u6301\u3061\u305f\u3044\uff01\n\nHeroku\n\u4ee5\u4e0b\u3092\u983c\u308a\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u308b\u3068\nhttps://devcenter.heroku.com/articles/container-registry-and-runtime\nheroku container:login\n\n\u3053\u3053\u306e\u90e8\u5206\u3067\u30a8\u30e9\u30fc\u767a\u751f\nevents.js:160\n      throw er; // Unhandled 'error' event\n      ^\n\nError: spawn docker ENOENT\n    at exports._errnoException (util.js:1007:11)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)\n    at onErrorNT (internal/child_process.js:348:16)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n    at Function.Module.runMain (module.js:577:11)\n    at startup (node.js:160:18)\n    at node.js:456:3\n\n\u30b0\u30b0\u3063\u3066\u3082\u30dd\u30fc\u30c8\u89e3\u653e\u3057\u3066\u306a\u3044\u3093\u3058\u3083\u306a\u3044\u3063\u3066\u3044\u3046\u65e8\u306e\u89e3\u6c7a\u7b56\u304c\u66f8\u3044\u3066\u3042\u3063\u3066\n\u89e3\u653e\u3057\u3066\u3082\u30c0\u30e1\u3067\u3057\u305f\u30fb\u30fb\u30fb\u3068\u3044\u3046\u3053\u3068\u3067heroku\u306f\u8f9e\u3081\uff01\n\u4e00\u4eba\u3067\u304a\u52c9\u5f37\u3059\u308b\u306b\u3082\u76ee\u6a19\u306a\u304f\u3084\u3063\u3066\u3044\u308b\u3068\u8272\u3093\u306a\u8a98\u60d1\u306b\u8ca0\u3051\u305d\u3046\u306b\u306a\u308b\u306e\u3067\n\u5b50\u4f9b\u306e\u3054\u8912\u7f8e\u30b7\u30fc\u30eb\u3068\u3044\u3046\u7a0b\u306e\u3082\u306e\u3067\u3082\u306a\u3044\u3051\u3069\u5de5\u7a0b\u7ba1\u7406\u3067\u9054\u6210\u611f\u3092\u6301\u3061\u305f\u3044\uff01\n\n## Heroku\n\u4ee5\u4e0b\u3092\u983c\u308a\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u308b\u3068\nhttps://devcenter.heroku.com/articles/container-registry-and-runtime\n\n```\nheroku container:login\n```\n\u3053\u3053\u306e\u90e8\u5206\u3067\u30a8\u30e9\u30fc\u767a\u751f\n\n```\nevents.js:160\n      throw er; // Unhandled 'error' event\n      ^\n\nError: spawn docker ENOENT\n    at exports._errnoException (util.js:1007:11)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)\n    at onErrorNT (internal/child_process.js:348:16)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)\n    at process._tickCallback (internal/process/next_tick.js:98:9)\n    at Function.Module.runMain (module.js:577:11)\n    at startup (node.js:160:18)\n    at node.js:456:3\n```\n\u30b0\u30b0\u3063\u3066\u3082\u30dd\u30fc\u30c8\u89e3\u653e\u3057\u3066\u306a\u3044\u3093\u3058\u3083\u306a\u3044\u3063\u3066\u3044\u3046\u65e8\u306e\u89e3\u6c7a\u7b56\u304c\u66f8\u3044\u3066\u3042\u3063\u3066\n\u89e3\u653e\u3057\u3066\u3082\u30c0\u30e1\u3067\u3057\u305f\u30fb\u30fb\u30fb\u3068\u3044\u3046\u3053\u3068\u3067heroku\u306f\u8f9e\u3081\uff01\n", "tags": ["Redmine"]}