{"context": "\n\n\u73fe\u8c61\nKinesis\u304b\u3089\u6765\u305f\u30c7\u30fc\u30bf\u3092BigQuery\u306b\u767b\u9332\u3059\u308bLambda\u95a2\u6570\u3092Python\u3067\u66f8\u3044\u3066\u30a2\u30c3\u30d7\u30ed\u30fc\u30c9\u5f8c\u3001\u51e6\u7406\u3092\u6d41\u3059\u3068\u4e0b\u8a18\u306e\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u305f\u3002\nNo module named google.protobuf: ImportError\nTraceback (most recent call last):\nFile \"/var/task/main.py\", line 17, in kinesis_event_bigquery_handler\ninsert_records(records)\nFile \"/var/task/main.py\", line 29, in insert_records\nfrom gcloud import bigquery\nFile \"/var/task/gcloud/bigquery/__init__.py\", line 24, in <module>\nfrom gcloud.bigquery.client import Client\nFile \"/var/task/gcloud/bigquery/client.py\", line 18, in <module>\nfrom gcloud.client import JSONClient\nFile \"/var/task/gcloud/client.py\", line 20, in <module>\nfrom gcloud._helpers import _determine_default_project\nFile \"/var/task/gcloud/_helpers.py\", line 26, in <module>\nfrom google.protobuf import timestamp_pb2\nImportError: No module named google.protobuf\n\n\n\u89e3\u6c7a\u7b56\n\u7a7a\u30d5\u30a1\u30a4\u30eb__init__.py\u3092google\u30d1\u30c3\u30b1\u30fc\u30b8\u306b\u8ffd\u52a0\u3059\u308b\u3002virtualenv\u3067\u74b0\u5883\u69cb\u7bc9\u3057\u3066\u3044\u308b\u5834\u5408\u306f\u3053\u3046\uff1a\n$ touch lib/python2.7/site-packages/google/__init__.py\n\nlambda-uploader\u3092\u5229\u7528\u3057\u3066\u3044\u308b\u5834\u5408\u306f\u3001\u30a2\u30c3\u30d7\u30ed\u30fc\u30c9\u306e\u969b--virtualenv\u3092\u5fd8\u308c\u305a\u306b\u3002\n$ lambda-uploader --virtualenv=.\n\n\n\u53c2\u8003\u6587\u732e\nhttps://github.com/awslabs/kinesis-deaggregation/blob/master/python/README.md\n# \u73fe\u8c61\nKinesis\u304b\u3089\u6765\u305f\u30c7\u30fc\u30bf\u3092BigQuery\u306b\u767b\u9332\u3059\u308bLambda\u95a2\u6570\u3092Python\u3067\u66f8\u3044\u3066\u30a2\u30c3\u30d7\u30ed\u30fc\u30c9\u5f8c\u3001\u51e6\u7406\u3092\u6d41\u3059\u3068\u4e0b\u8a18\u306e\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3057\u305f\u3002\n\n```pytb\nNo module named google.protobuf: ImportError\nTraceback (most recent call last):\nFile \"/var/task/main.py\", line 17, in kinesis_event_bigquery_handler\ninsert_records(records)\nFile \"/var/task/main.py\", line 29, in insert_records\nfrom gcloud import bigquery\nFile \"/var/task/gcloud/bigquery/__init__.py\", line 24, in <module>\nfrom gcloud.bigquery.client import Client\nFile \"/var/task/gcloud/bigquery/client.py\", line 18, in <module>\nfrom gcloud.client import JSONClient\nFile \"/var/task/gcloud/client.py\", line 20, in <module>\nfrom gcloud._helpers import _determine_default_project\nFile \"/var/task/gcloud/_helpers.py\", line 26, in <module>\nfrom google.protobuf import timestamp_pb2\nImportError: No module named google.protobuf\n```\n\n# \u89e3\u6c7a\u7b56\n\u7a7a\u30d5\u30a1\u30a4\u30eb`__init__.py`\u3092google\u30d1\u30c3\u30b1\u30fc\u30b8\u306b\u8ffd\u52a0\u3059\u308b\u3002virtualenv\u3067\u74b0\u5883\u69cb\u7bc9\u3057\u3066\u3044\u308b\u5834\u5408\u306f\u3053\u3046\uff1a\n\n```shell-session\n$ touch lib/python2.7/site-packages/google/__init__.py\n```\n\n[lambda-uploader](https://github.com/rackerlabs/lambda-uploader)\u3092\u5229\u7528\u3057\u3066\u3044\u308b\u5834\u5408\u306f\u3001\u30a2\u30c3\u30d7\u30ed\u30fc\u30c9\u306e\u969b`--virtualenv`\u3092\u5fd8\u308c\u305a\u306b\u3002\n\n```shell-session\n$ lambda-uploader --virtualenv=.\n```\n\n# \u53c2\u8003\u6587\u732e\nhttps://github.com/awslabs/kinesis-deaggregation/blob/master/python/README.md\n\n", "tags": ["AWS", "lambda", "Python", "bigquery"]}