{"tags": ["Jupyter"], "context": "jupyter\u306b\u3066\u300cDead Kernel\u300d\u3068\u30ab\u30fc\u30cd\u30eb\u304c\u52dd\u624b\u306b\u843d\u3061\u308b\u73fe\u8c61\u304c\u3042\u3063\u3066\u3001\n\u539f\u56e0\u304c\u308f\u304b\u3089\u305a\u82e6\u52b4\u3057\u305f\u306e\u3067\u30e1\u30e2\u3057\u3066\u304a\u304d\u307e\u3059\u3002\n\n\uff1c\u30a8\u30e9\u30fc\u306e\u5185\u5bb9\uff1e\nTraceback (most recent call last):\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 174, in _run_module_as_main\n    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 133, in _get_module_details\n    return _get_module_details(pkg_main_name, error)\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 109, in _get_module_details\n    __import__(pkg_name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\__init__.py\", line 2, in <module>\n    from .connect import *\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\connect.py\", line 13, in <module>\n    from IPython.core.profiledir import ProfileDir\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\__init__.py\", line 48, in <module>\n    from .core.application import Application\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\application.py\", line 23, in <module>\n    from traitlets.config.application import Application, catch_config_error\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\__init__.py\", line 1, in <module>\n    from .traitlets import *\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\traitlets.py\", line 944, in <module>\n    class HasDescriptors(six.with_metaclass(MetaHasDescriptors, object)):\n  File \"C:\\Anaconda3\\lib\\site-packages\\six.py\", line 808, in __new__\n    return meta(name, bases, d)\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\traitlets.py\", line 726, in __new__\n    if inspect.isclass(v) and issubclass(v, TraitType):\nAttributeError: module 'inspect' has no attribute 'isclass'\n\n\u539f\u56e0\u306finspect.py\u3068\u3044\u3046\u30d5\u30a1\u30a4\u30eb\u3092\u4f5c\u3063\u305f\u3053\u3068\u306b\u3042\u308a\u307e\u3057\u305f\u3002\n\u9069\u5f53\u306ainspect.py\u3092\u4f5c\u3063\u3066\u3001\u540c\u3058\u30d5\u30a9\u30eb\u30c0\u3067.ipynb\u30d5\u30a1\u30a4\u30eb\u3092\u52d5\u304b\u3059\u3068\u30ab\u30fc\u30cd\u30eb\u304c\u843d\u3061\u307e\u3059\u3002\ninspect.py\u306f\u6a19\u6e96\u306e\u30e9\u30a4\u30d6\u30e9\u30ea\u306b\u3042\u308b\u3089\u3057\u304f\u3001\u91cd\u8907\u3057\u305f\u305f\u3081\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u3088\u3046\u3067\u3059\u3002\njupyter\u306b\u3066\u300cDead Kernel\u300d\u3068\u30ab\u30fc\u30cd\u30eb\u304c\u52dd\u624b\u306b\u843d\u3061\u308b\u73fe\u8c61\u304c\u3042\u3063\u3066\u3001\n\u539f\u56e0\u304c\u308f\u304b\u3089\u305a\u82e6\u52b4\u3057\u305f\u306e\u3067\u30e1\u30e2\u3057\u3066\u304a\u304d\u307e\u3059\u3002\n\n![image](https://qiita-image-store.s3.amazonaws.com/0/109458/2861c555-15bf-be49-534f-96263e4a63d7.png)\n\n\n\uff1c\u30a8\u30e9\u30fc\u306e\u5185\u5bb9\uff1e\n\n```\nTraceback (most recent call last):\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 174, in _run_module_as_main\n    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 133, in _get_module_details\n    return _get_module_details(pkg_main_name, error)\n  File \"C:\\Anaconda3\\lib\\runpy.py\", line 109, in _get_module_details\n    __import__(pkg_name)\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\__init__.py\", line 2, in <module>\n    from .connect import *\n  File \"C:\\Anaconda3\\lib\\site-packages\\ipykernel\\connect.py\", line 13, in <module>\n    from IPython.core.profiledir import ProfileDir\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\__init__.py\", line 48, in <module>\n    from .core.application import Application\n  File \"C:\\Anaconda3\\lib\\site-packages\\IPython\\core\\application.py\", line 23, in <module>\n    from traitlets.config.application import Application, catch_config_error\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\__init__.py\", line 1, in <module>\n    from .traitlets import *\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\traitlets.py\", line 944, in <module>\n    class HasDescriptors(six.with_metaclass(MetaHasDescriptors, object)):\n  File \"C:\\Anaconda3\\lib\\site-packages\\six.py\", line 808, in __new__\n    return meta(name, bases, d)\n  File \"C:\\Anaconda3\\lib\\site-packages\\traitlets\\traitlets.py\", line 726, in __new__\n    if inspect.isclass(v) and issubclass(v, TraitType):\nAttributeError: module 'inspect' has no attribute 'isclass'\n```\n\n\n\u539f\u56e0\u306finspect.py\u3068\u3044\u3046\u30d5\u30a1\u30a4\u30eb\u3092\u4f5c\u3063\u305f\u3053\u3068\u306b\u3042\u308a\u307e\u3057\u305f\u3002\n\u9069\u5f53\u306ainspect.py\u3092\u4f5c\u3063\u3066\u3001\u540c\u3058\u30d5\u30a9\u30eb\u30c0\u3067.ipynb\u30d5\u30a1\u30a4\u30eb\u3092\u52d5\u304b\u3059\u3068\u30ab\u30fc\u30cd\u30eb\u304c\u843d\u3061\u307e\u3059\u3002\ninspect.py\u306f\u6a19\u6e96\u306e\u30e9\u30a4\u30d6\u30e9\u30ea\u306b\u3042\u308b\u3089\u3057\u304f\u3001\u91cd\u8907\u3057\u305f\u305f\u3081\u30a8\u30e9\u30fc\u304c\u51fa\u305f\u3088\u3046\u3067\u3059\u3002\n\n\n\n"}