{"context": "\n\n\u80cc\u666f\naplaca\u3055\u3093\u306eLabellio\u3068\u3044\u3046\u4fbf\u5229\u306a\u30b5\u30fc\u30d3\u30b9\u3092\u4f7f\u3063\u3066\u4f5c\u3063\u305f\u30e2\u30c7\u30eb\u3092\u81ea\u5206\u306e\u30b5\u30fc\u30d0\u30fc\u306b\u8f09\u305b\u305f\u3044\u3068\u601d\u3044\u307e\u3057\u305f\u304c\u3001Caffe\u306e\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u6642(\uff1f\uff09\u306b\u30cf\u30de\u3063\u305f\u306e\u3067\u3001\u89e3\u6c7a\u7b56\u3092\u30e1\u30e2\u3057\u3066\u304a\u304d\u307e\u3059\u3002\n\n\u6ce8\u610f\n\u539f\u56e0\u306e\u7a76\u660e\u307e\u3067\u51fa\u6765\u3066\u3044\u307e\u305b\u3093\u3002\n\u3053\u3093\u306a\u72b6\u614b\u3067\u66d6\u6627\u306a\u60c5\u5831\u3092\u516c\u958b\u3059\u308b\u306e\u306f\u826f\u304f\u306a\u3044\u3068\u601d\u3044\u307e\u3059\u304c\u3001\u540c\u3058\u72b6\u614b\u3067\u56f0\u3063\u3066\u3044\u308b\u4eba\u304c\u5c45\u308b\u304b\u3082\u3057\u308c\u307e\u305b\u3093\u306e\u3067\u3001\u5bfe\u51e6\u6cd5\u3068\u3057\u3066\u516c\u958b\u3057\u3066\u304a\u304d\u307e\u3059\u3002\n\n\u74b0\u5883\u69cb\u7bc9\uff06\u554f\u984c\u306b\u3076\u3064\u304b\u308b\u307e\u3067\u306e\u6d41\u308c\n\nlabbelio\u3067\u5206\u985e\u5668\u4f5c\u3063\u3066\u307f\u305f\n\u4f5c\u3063\u305f\u30e2\u30c7\u30eb\u3092Web\u3067\u516c\u958b\u3057\u305f\u3044\uff08\u516c\u958b\u306e\u65b9\u6cd5\u306f\u3053\u3061\u3089\uff09\nubuntu\u30b5\u30fc\u30d0\u30fc\u6301\u3063\u3066\u306a\u3044\nCentOS6\u3067\u9811\u5f35\u308d\u3046\u3068\u3057\u305f\u304c\u632b\u6298\u3057\u305f\nkonoha\u3067ubuntu14.04\u3092\u501f\u308a\u305f\n\n\u3053\u3061\u3089\u306e\u8a18\u4e8b\u3092\u53c2\u8003\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u3063\u305f\ncaffe\u306e\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306f\u51fa\u6765\u305f\uff08\u300cmake runtest\u300d\u306f\u901a\u3063\u305f\uff09\napp.py\u3092\u5b9f\u884c\u3059\u308b\u3068\u3001\u3053\u3093\u306a\u30a8\u30e9\u30fc\u51fa\u305f\n\nGdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed\nTraceback (most recent call last):\n  File \"app.py\", line 8, in <module>\n    from labellio import Classifier, Config, ImageLoader, Label\n  File \"/usr/local/lib/python2.7/dist-packages/labellio/__init__.py\", line 2, in <module>\n    from labellio.classifier import Classifier\n  File \"/usr/local/lib/python2.7/dist-packages/labellio/classifier.py\", line 6, in <module>\n    from labellio.net import Net\n  File \"/usr/local/lib/python2.7/dist-packages/labellio/net.py\", line 4, in <module>\n    import caffe\n  File \"/root/caffe/python/caffe/__init__.py\", line 1, in <module>\n    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver\n  File \"/root/caffe/python/caffe/pycaffe.py\", line 15, in <module>\n    import caffe.io\n  File \"/root/caffe/python/caffe/io.py\", line 2, in <module>\n    import skimage.io\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/__init__.py\", line 15, in <module>\n    reset_plugins()\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 93, in reset_plugins\n    _load_preferred_plugins()\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 73, in _load_preferred_plugins\n    _set_plugin(p_type, preferred_plugins['all'])\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 85, in _set_plugin\n    use_plugin(plugin, kind=plugin_type)\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 255, in use_plugin\n    _load(name)\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 299, in _load\n    fromlist=[modname])\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/matplotlib_plugin.py\", line 3, in <module>\n    import matplotlib.pyplot as plt\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py\", line 114, in <module>\n    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py\", line 32, in pylab_setup\n    globals(),locals(),[backend_name],0)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3agg.py\", line 11, in <module>\n    from . import backend_gtk3\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3.py\", line 58, in <module>\n    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),\nTypeError: constructor returned NULL\n\n\n\u89e3\u6c7a\u7b56\nhttps://github.com/BVLC/caffe/issues/861\n\u3053\u3053\u3092\u53c2\u8003\u306b\u3057\u3066\u3001\u5b9f\u884c\u6642\u306bMPLBACKEND=Agg\u3092\u4ed8\u3051\u308b\u3068\u52d5\u304d\u307e\u3057\u305f\u3002\n\u3053\u3093\u306a\u611f\u3058\u2192\u300cMPLBACKEND=Agg python app.py\u300d\n#\u80cc\u666f\naplaca\u3055\u3093\u306e[Labellio](https://www.labell.io/)\u3068\u3044\u3046\u4fbf\u5229\u306a\u30b5\u30fc\u30d3\u30b9\u3092\u4f7f\u3063\u3066\u4f5c\u3063\u305f\u30e2\u30c7\u30eb\u3092\u81ea\u5206\u306e\u30b5\u30fc\u30d0\u30fc\u306b\u8f09\u305b\u305f\u3044\u3068\u601d\u3044\u307e\u3057\u305f\u304c\u3001Caffe\u306e\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u6642(\uff1f\uff09\u306b\u30cf\u30de\u3063\u305f\u306e\u3067\u3001\u89e3\u6c7a\u7b56\u3092\u30e1\u30e2\u3057\u3066\u304a\u304d\u307e\u3059\u3002\n\n#\u6ce8\u610f\n\u539f\u56e0\u306e\u7a76\u660e\u307e\u3067\u51fa\u6765\u3066\u3044\u307e\u305b\u3093\u3002\n\u3053\u3093\u306a\u72b6\u614b\u3067\u66d6\u6627\u306a\u60c5\u5831\u3092\u516c\u958b\u3059\u308b\u306e\u306f\u826f\u304f\u306a\u3044\u3068\u601d\u3044\u307e\u3059\u304c\u3001\u540c\u3058\u72b6\u614b\u3067\u56f0\u3063\u3066\u3044\u308b\u4eba\u304c\u5c45\u308b\u304b\u3082\u3057\u308c\u307e\u305b\u3093\u306e\u3067\u3001\u5bfe\u51e6\u6cd5\u3068\u3057\u3066\u516c\u958b\u3057\u3066\u304a\u304d\u307e\u3059\u3002\n\n#\u74b0\u5883\u69cb\u7bc9\uff06\u554f\u984c\u306b\u3076\u3064\u304b\u308b\u307e\u3067\u306e\u6d41\u308c\n1. labbelio\u3067\u5206\u985e\u5668\u4f5c\u3063\u3066\u307f\u305f\n2. \u4f5c\u3063\u305f\u30e2\u30c7\u30eb\u3092Web\u3067\u516c\u958b\u3057\u305f\u3044\uff08\u516c\u958b\u306e\u65b9\u6cd5\u306f[\u3053\u3061\u3089](http://blog-jp.alpaca.ai/entry/2015/06/30/135214)\uff09\n3. ubuntu\u30b5\u30fc\u30d0\u30fc\u6301\u3063\u3066\u306a\u3044\n- CentOS6\u3067\u9811\u5f35\u308d\u3046\u3068\u3057\u305f\u304c\u632b\u6298\u3057\u305f\n- konoha\u3067ubuntu14.04\u3092\u501f\u308a\u305f\n- [\u3053\u3061\u3089\u306e\u8a18\u4e8b](http://qiita.com/TD72/items/1bab76e395243defcc06)\u3092\u53c2\u8003\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u3063\u305f\n- caffe\u306e\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306f\u51fa\u6765\u305f\uff08\u300cmake runtest\u300d\u306f\u901a\u3063\u305f\uff09\n- app.py\u3092\u5b9f\u884c\u3059\u308b\u3068\u3001\u3053\u3093\u306a\u30a8\u30e9\u30fc\u51fa\u305f\n\n```\nGdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed\nTraceback (most recent call last):\n  File \"app.py\", line 8, in <module>\n    from labellio import Classifier, Config, ImageLoader, Label\n  File \"/usr/local/lib/python2.7/dist-packages/labellio/__init__.py\", line 2, in <module>\n    from labellio.classifier import Classifier\n  File \"/usr/local/lib/python2.7/dist-packages/labellio/classifier.py\", line 6, in <module>\n    from labellio.net import Net\n  File \"/usr/local/lib/python2.7/dist-packages/labellio/net.py\", line 4, in <module>\n    import caffe\n  File \"/root/caffe/python/caffe/__init__.py\", line 1, in <module>\n    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver\n  File \"/root/caffe/python/caffe/pycaffe.py\", line 15, in <module>\n    import caffe.io\n  File \"/root/caffe/python/caffe/io.py\", line 2, in <module>\n    import skimage.io\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/__init__.py\", line 15, in <module>\n    reset_plugins()\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 93, in reset_plugins\n    _load_preferred_plugins()\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 73, in _load_preferred_plugins\n    _set_plugin(p_type, preferred_plugins['all'])\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 85, in _set_plugin\n    use_plugin(plugin, kind=plugin_type)\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 255, in use_plugin\n    _load(name)\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/manage_plugins.py\", line 299, in _load\n    fromlist=[modname])\n  File \"/usr/local/lib/python2.7/dist-packages/skimage/io/_plugins/matplotlib_plugin.py\", line 3, in <module>\n    import matplotlib.pyplot as plt\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py\", line 114, in <module>\n    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py\", line 32, in pylab_setup\n    globals(),locals(),[backend_name],0)\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3agg.py\", line 11, in <module>\n    from . import backend_gtk3\n  File \"/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_gtk3.py\", line 58, in <module>\n    cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),\nTypeError: constructor returned NULL\n```\n\n#\u89e3\u6c7a\u7b56\nhttps://github.com/BVLC/caffe/issues/861\n\u3053\u3053\u3092\u53c2\u8003\u306b\u3057\u3066\u3001\u5b9f\u884c\u6642\u306b**MPLBACKEND=Agg\u3092\u4ed8\u3051\u308b**\u3068\u52d5\u304d\u307e\u3057\u305f\u3002\n\n\u3053\u3093\u306a\u611f\u3058\u2192\u300c**MPLBACKEND=Agg python app.py**\u300d\n", "tags": ["DeepLearning", "Python", "matplotlib", "Caffe", "Ubuntu"]}