{"context": " More than 1 year has passed since last update.\u3000Conoha VPS\u3078[\u6a19\u6e96OS]Cent OS 6.4 (64bit)\u3092\u9078\u629e\u3057\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u305f\u5f8c\u306b\u3001yum update\u3092\u5b9f\u884c\u3057\u30a2\u30c3\u30d7\u30c7\u30fc\u30c8\u3059\u308b\u3068\u8d77\u52d5\u51e6\u7406\u306b+4\u5206\u304b\u304b\u308b\u3088\u3046\u306b\u306a\u308a\u307e\u3059\u3002\n\u3053\u306e\u73fe\u8c61\u306f\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u6e08\u307f\u30d1\u30c3\u30b1\u30fc\u30b8\u306b\u542b\u307e\u308c\u308b\u300cCloud-init\u300d\u306e\u8a2d\u5b9a\u304c\u3001\u521d\u671f\u72b6\u614b\u3067\u6a5f\u80fd\u3057\u306a\u3044\u305f\u3081\u306b\u8b66\u544a\u3092\u51fa\u3057\u307e\u3059\u3002\n2014-04-28 22:30:19,146 - url_helper.py[WARNING]: Calling 'http://169.254.169.2542009-04-04/meta-data/instance-id' failed [50/120s]:request error HTTPConnectionPool(host='169.254.169.254', port=80): Request \ntimed out. (timeout=50.0)]\n2014-04-28 22:31:10,202 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [101/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Reques t timed out. (timeout=50.0)]\n\u4ee5\u4e0b\u7701\u7565\n\nCloud-init\u30d1\u30c3\u30b1\u30fc\u30b8\u306f\u3001Conoha VPS\u3067\u306f\u4f7f\u7528\u3057\u306a\u3044\u305f\u3081\u3001\u524a\u9664\u3057\u3066\u3082\u554f\u984c\u306f\u3042\u308a\u307e\u305b\u3093\u3002\n\u3088\u3063\u3066\u6b21\u306e\u30b3\u30de\u30f3\u30c9\u3067\u524a\u9664\u3059\u308c\u3070\u89e3\u6c7a\u3057\u307e\u3059\u3002\nrpm -e cloud-init \n\u307e\u305f\u306f\nyum remove cloud-init\n\n\u3000Conoha VPS\u3078[\u6a19\u6e96OS]Cent OS 6.4 (64bit)\u3092\u9078\u629e\u3057\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u305f\u5f8c\u306b\u3001yum update\u3092\u5b9f\u884c\u3057\u30a2\u30c3\u30d7\u30c7\u30fc\u30c8\u3059\u308b\u3068\u8d77\u52d5\u51e6\u7406\u306b+4\u5206\u304b\u304b\u308b\u3088\u3046\u306b\u306a\u308a\u307e\u3059\u3002\n\u3053\u306e\u73fe\u8c61\u306f\u3001\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u6e08\u307f\u30d1\u30c3\u30b1\u30fc\u30b8\u306b\u542b\u307e\u308c\u308b\u300cCloud-init\u300d\u306e\u8a2d\u5b9a\u304c\u3001\u521d\u671f\u72b6\u614b\u3067\u6a5f\u80fd\u3057\u306a\u3044\u305f\u3081\u306b\u8b66\u544a\u3092\u51fa\u3057\u307e\u3059\u3002\n\n```log\n2014-04-28 22:30:19,146 - url_helper.py[WARNING]: Calling 'http://169.254.169.2542009-04-04/meta-data/instance-id' failed [50/120s]:request error HTTPConnectionPool(host='169.254.169.254', port=80): Request \ntimed out. (timeout=50.0)]\n2014-04-28 22:31:10,202 - url_helper.py[WARNING]: Calling 'http://169.254.169.254/2009-04-04/meta-data/instance-id' failed [101/120s]: request error [HTTPConnectionPool(host='169.254.169.254', port=80): Reques t timed out. (timeout=50.0)]\n\u4ee5\u4e0b\u7701\u7565\n```\n\nCloud-init\u30d1\u30c3\u30b1\u30fc\u30b8\u306f\u3001Conoha VPS\u3067\u306f\u4f7f\u7528\u3057\u306a\u3044\u305f\u3081\u3001\u524a\u9664\u3057\u3066\u3082\u554f\u984c\u306f\u3042\u308a\u307e\u305b\u3093\u3002\n\u3088\u3063\u3066\u6b21\u306e\u30b3\u30de\u30f3\u30c9\u3067\u524a\u9664\u3059\u308c\u3070\u89e3\u6c7a\u3057\u307e\u3059\u3002\nrpm -e cloud-init \n\u307e\u305f\u306f\nyum remove cloud-init\n\n\n\n\n\n\n", "tags": ["Conoha", "vps", "CentOS6.5"]}