{"tags": ["CircleCI", "ElasticBeanstalk", "pip"], "context": "\n\nTL;DR\n\nCircleCI\u304b\u3089ElasticBeanstalk\u306b\u30c7\u30d7\u30ed\u30a4\u3059\u308b\u305f\u3081\u306b awsebcli \u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u308b\u74b0\u5883\n\nawsebcli \u304c version 3.7.5 \u306b\u306a\u3063\u305f\u3053\u3068\u3067\u30b3\u30b1\u308b\u3088\u3046\u306b\u306a\u3063\u305f\nversion\u3092\u56fa\u5b9a\u3059\u308b\u3053\u3068\u3067\u56de\u907f\n\n\n\u8ffd\u8a18\u4fee\u6b63\n\npython\u306eversion\u3092\u4e0a\u3052\u308b\u4e8b\u3067\u56de\u907f\u3067\u304d\u308b\u3088\u3046\u306a\u306e\u3067\u4fee\u6b63\n\n\n\u30a8\u30e9\u30fc\u5185\u5bb9\nsudo pip install --upgrade -q awsebcli\n/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.\n  SNIMissingWarning\n/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.\n  InsecurePlatformWarning\nTraceback (most recent call last):\n  File \"/usr/local/bin/pip\", line 9, in <module>\n    load_entry_point('pip==8.1.1', 'console_scripts', 'pip')()\n  File \"/usr/local/lib/python2.7/dist-packages/pip/__init__.py\", line 217, in main\n    return command.main(cmd_args)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/basecommand.py\", line 246, in main\n    pip_version_check(session)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/utils/outdated.py\", line 102, in pip_version_check\n    installed_version = get_installed_version(\"pip\")\n  File \"/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py\", line 848, in get_installed_version\n    working_set = pkg_resources.WorkingSet()\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 626, in __init__\n    self.add_entry(entry)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 682, in add_entry\n    for dist in find_distributions(entry, True):\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 2080, in find_eggs_in_zip\n    if metadata.has_metadata('PKG-INFO'):\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 1610, in has_metadata\n    return self.egg_info and self._has(self._fn(self.egg_info, name))\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 1968, in _has\n    return zip_path in self.zipinfo or zip_path in self._index()\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 1848, in zipinfo\n    return self._zip_manifests.load(self.loader.archive)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 1788, in load\n    mtime = os.stat(path).st_mtime\nOSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/setuptools-3.4.4-py2.7.egg'\n\nsudo pip install --upgrade -q awsebcli returned exit code 1\n\nAction failed: sudo pip install --upgrade -q awsebcli\n\n\n\u3082\u3068\u3082\u3068\u306e\u8a2d\u5b9a\n\ncircle.yml\nmachine:\n  timezone:\n    Asia/Tokyo\n\n~~ snip ~~\n\ndependencies:\n  pre:\n    - 'sudo pip install -q awsebcli'\n\n~~ snip ~~\n\n\n\n\n\u56de\u907f\u65b9\u6cd5: awsebcli\u306eversion\u3092\u56fa\u5b9a\u3059\u308b\u65b9\u6cd5\n\ncircle.yml\nmachine:\n  timezone:\n    Asia/Tokyo\n\n~~ snip ~~\n\ndependencies:\n  pre:\n    - 'sudo pip install -q awsebcli==3.7.4'\n\n~~ snip ~~\n\n\n\n\n\u56de\u907f\u65b9\u6cd5: python\u306eversion\u3092\u4e0a\u3052\u308b\u65b9\u6cd5\n\ncircle.yml\nmachine:\n  python:\n    version: 2.7.9\n  timezone:\n    Asia/Tokyo\n\n~~ snip ~~\n\ndependencies:\n  pre:\n    - pip install awsebcli\n\n~~ snip ~~\n\n\n\n# TL;DR\n- CircleCI\u304b\u3089ElasticBeanstalk\u306b\u30c7\u30d7\u30ed\u30a4\u3059\u308b\u305f\u3081\u306b ```awsebcli``` \u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u308b\u74b0\u5883\n- ``` awsebcli ``` \u304c version ```3.7.5 ``` \u306b\u306a\u3063\u305f\u3053\u3068\u3067\u30b3\u30b1\u308b\u3088\u3046\u306b\u306a\u3063\u305f\n- ~~version\u3092\u56fa\u5b9a\u3059\u308b\u3053\u3068\u3067\u56de\u907f~~\n\n## \u8ffd\u8a18\u4fee\u6b63\n- python\u306eversion\u3092\u4e0a\u3052\u308b\u4e8b\u3067\u56de\u907f\u3067\u304d\u308b\u3088\u3046\u306a\u306e\u3067\u4fee\u6b63\n\n\n# \u30a8\u30e9\u30fc\u5185\u5bb9\n\n```\nsudo pip install --upgrade -q awsebcli\n/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.\n  SNIMissingWarning\n/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.\n  InsecurePlatformWarning\nTraceback (most recent call last):\n  File \"/usr/local/bin/pip\", line 9, in <module>\n    load_entry_point('pip==8.1.1', 'console_scripts', 'pip')()\n  File \"/usr/local/lib/python2.7/dist-packages/pip/__init__.py\", line 217, in main\n    return command.main(cmd_args)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/basecommand.py\", line 246, in main\n    pip_version_check(session)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/utils/outdated.py\", line 102, in pip_version_check\n    installed_version = get_installed_version(\"pip\")\n  File \"/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py\", line 848, in get_installed_version\n    working_set = pkg_resources.WorkingSet()\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 626, in __init__\n    self.add_entry(entry)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 682, in add_entry\n    for dist in find_distributions(entry, True):\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 2080, in find_eggs_in_zip\n    if metadata.has_metadata('PKG-INFO'):\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 1610, in has_metadata\n    return self.egg_info and self._has(self._fn(self.egg_info, name))\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 1968, in _has\n    return zip_path in self.zipinfo or zip_path in self._index()\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 1848, in zipinfo\n    return self._zip_manifests.load(self.loader.archive)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/pkg_resources/__init__.py\", line 1788, in load\n    mtime = os.stat(path).st_mtime\nOSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/setuptools-3.4.4-py2.7.egg'\n\nsudo pip install --upgrade -q awsebcli returned exit code 1\n\nAction failed: sudo pip install --upgrade -q awsebcli\n```\n\n# \u3082\u3068\u3082\u3068\u306e\u8a2d\u5b9a\n\n```circle.yml\nmachine:\n  timezone:\n    Asia/Tokyo\n\n~~ snip ~~\n\ndependencies:\n  pre:\n    - 'sudo pip install -q awsebcli'\n    \n~~ snip ~~\n\n```\n\n\n# \u56de\u907f\u65b9\u6cd5: awsebcli\u306eversion\u3092\u56fa\u5b9a\u3059\u308b\u65b9\u6cd5\n\n```circle.yml\nmachine:\n  timezone:\n    Asia/Tokyo\n\n~~ snip ~~\n\ndependencies:\n  pre:\n    - 'sudo pip install -q awsebcli==3.7.4'\n    \n~~ snip ~~\n\n```\n\n# \u56de\u907f\u65b9\u6cd5: python\u306eversion\u3092\u4e0a\u3052\u308b\u65b9\u6cd5\n\n```circle.yml\nmachine:\n  python:\n    version: 2.7.9\n  timezone:\n    Asia/Tokyo\n  \n~~ snip ~~\n\ndependencies:\n  pre:\n    - pip install awsebcli\n    \n~~ snip ~~\n\n```\n\n"}