{"context": "\n\n\u3084\u308b\u3053\u3068\nPython\u30d7\u30ed\u30b0\u30e9\u30e0\u304b\u3089Google Spreadsheet\u306b\u30a2\u30af\u30bb\u30b9\u3059\u308b\u307e\u3067\u306b\u767a\u751f\u3057\u305f\u554f\u984c\u3068\u3001\u305d\u306e\u5bfe\u7b56\u306e\u899a\u66f8\u3002\n\n\u65b9\u6cd5\nGoogle Spreadsheet\u3092\u8aad\u307f\u66f8\u304d\u3059\u308b\u305f\u3081\u306ePython\u30e9\u30a4\u30d6\u30e9\u30ea\u3067\u3042\u308bgspread\u3092\u4f7f\u3046\u3002\nhttps://github.com/burnash/gspread\n\ngspread\u306e\u4f7f\u3044\u65b9\n\u3042\u3089\u304b\u3058\u3081\u3001testbook\u3068\u3044\u3046\u540d\u524d\u306e\u30b9\u30d7\u30ec\u30c3\u30c9\u30b7\u30fc\u30c8\u3092Google Spreadsheet\u4e0a\u306b\u4f5c\u6210\u3057\u305f\u3002\n\u30a2\u30af\u30bb\u30b9\u306f\nhttp://gspread.readthedocs.org/en/latest/oauth2.html\n\u306e\u901a\u308a\u306b\u3002\n\u307b\u307c\u30b5\u30f3\u30d7\u30eb\u305d\u306e\u307e\u307e\u306e\u4ee5\u4e0b\u3092\u5b9f\u884c\u3059\u308b\u3002\n    import gspread\n    from oauth2client.service_account import ServiceAccountCredentials\n\n    scope = ['https://spreadsheets.google.com/feeds']\n    credentials = ServiceAccountCredentials.from_json_keyfile_name(\n        'sample-xxxxxx.json', scope)\n\n    gc = gspread.authorize(credentials)\n    wks = gc.open(\"testbook\")\n\n\u8aad\u307f\u66f8\u304d\u306e\u6e96\u5099\u3068\u3057\u3066Google spreadsheet\u4e0a\u306b\u3042\u308b\u30b9\u30d7\u30ec\u30c3\u30c9\u30b7\u30fc\u30c8\u3092\u958b\u304f\u3060\u3051\u3002\n\u304c\u3001\u5931\u6557\u3057\u305f\u3002\n\u4ee5\u4e0b\u3001\u4e0a\u8a18\u3092\u52d5\u304b\u3059\u307e\u3067\u306b\u767a\u751f\u3057\u305f\u8907\u6570\u306e\u554f\u984c\u305d\u308c\u305e\u308c\u306b\u3064\u3044\u3066\u3001\u5185\u5bb9\u3068\u305d\u306e\u5bfe\u7b56\u3002\n\n\u30c8\u30e9\u30d6\u30eb\u30b7\u30e5\u30fc\u30c6\u30a3\u30f3\u30b0\n\noauth2client.client.HttpAccessTokenRefreshError\n\u307e\u305a\u51fa\u305f\u30a8\u30e9\u30fc\nTraceback (most recent call last):\n(\u4e2d\u7565)\n    gc = gspread.authorize(credentials)\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 331, in authorize\n    client.login()\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 101, in login\n    self.auth.refresh(http)\n  File \"/usr/local/lib/python2.7/dist-packages/oauth2client/client.py\", line 659, in refresh\n    self._refresh(http.request)\n  File \"/usr/local/lib/python2.7/dist-packages/oauth2client/client.py\", line 864, in _refresh\n    self._do_refresh_request(http_request)\n  File \"/usr/local/lib/python2.7/dist-packages/oauth2client/client.py\", line 933, in _do_refresh_request\n    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)\noauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Invalid JWT: Token must be a short-lived token and in a reasonable timeframe\n\n\u539f\u56e0\u306f\u6642\u523b\u540c\u671f\u304c\u3055\u308c\u305f\u3044\u306a\u304b\u3063\u305f\u3053\u3068(\u5b9f\u6642\u9593\u3088\u308a\u9045\u308c\u3066\u3044\u305f)\u3002\n\u6642\u523b\u3092\u540c\u671f\u5f8c\u306b\u518d\u5ea6\u5b9f\u884c\u3059\u308b\u3068\noauth2client.client.HttpAccessTokenRefreshError\u306f\u51fa\u306a\u304f\u306a\u3063\u305f\u3002\ngoogle api - Token must be a short-lived token and in a reasonable timeframe - Stack Overflow\nhttp://stackoverflow.com/questions/36189612/token-must-be-a-short-lived-token-and-in-a-reasonable-timeframe\n\u304c\u3001\u5225\u306e\u30a8\u30e9\u30fc\u3067\u5931\u6557\u3002\n\nrequests.exceptions.SSLError\nTraceback (most recent call last):\n(\u4e2d\u7565)\n    wks = gc.open(\"testbook\")\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 145, in open\n    feed = self.get_spreadsheets_feed()\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 231, in get_spreadsheets_feed\n    r = self.session.get(url)\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py\", line 75, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py\", line 67, in request\n    response = func(url, data=data, headers=request_headers)\n  File \"/usr/lib/python2.7/dist-packages/requests/api.py\", line 60, in get\n    return request('get', url, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/api.py\", line 49, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/sessions.py\", line 457, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/sessions.py\", line 569, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/adapters.py\", line 420, in send\n    raise SSLError(e, request=request)\nrequests.exceptions.SSLError\n\npython 2.7\u7cfb\u3060\u3068\u767a\u751f\u3059\u308b\uff1fPython 3.5.1\u3067\u306f\u767a\u751f\u3057\u306a\u304b\u3063\u305f\u3002\npython 2.7\u3067\u306e\u5f53\u9762\u306e\u5bfe\u7b56\u306f\u65e7\u30d0\u30fc\u30b8\u30e7\u30f3\u306ecertifi\u3092\u5165\u308c\u308b\u3053\u3068\u3002\npip uninstall -y certifi && pip install certifi==2015.04.28\n\nssl - SSL3_GET_SERVER_CERTIFICATE certificate verify failed on Python when requesting (only) *.google.com - Stack Overflow\nhttp://stackoverflow.com/questions/34646942/ssl3-get-server-certificate-certificate-verify-failed-on-python-when-requesting\n\u5143\u3005\u5165\u3063\u3066\u3044\u305fcertifi\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u306f\npip list | grep certifi\ncertifi (2015.11.20.1)\n\n\u518d\u5b9f\u884c\u3059\u308b\u3068\u3001requests.exceptions.SSLError\u306f\u51fa\u306a\u304f\u306a\u3063\u305f\u304c\u3001\u307e\u305f\u5225\u306e\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3002\n\nSpreadsheetNotFound\nTraceback (most recent call last):\n(\u4e2d\u7565)\n    wks = gc.open(\"testbook\")\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 152, in open\n    raise SpreadsheetNotFound\ngspread.exceptions.SpreadsheetNotFound\n\ngspread\u306e\u30c9\u30ad\u30e5\u30e1\u30f3\u30c8\u306b\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u4e00\u6587\u304c\u3042\u308b\u3002\nUsing OAuth2 for Authorization \u2014 gspread 0.3.0 documentation\nhttp://gspread.readthedocs.org/en/latest/oauth2.html\n\nGo to Google Sheets and share your spreadsheet with an email you have in your json_key['client_email']. Otherwise you\u2019ll get a SpreadsheetNotFound exception when trying to open it.\n\n\u3053\u308c\u306e\u901a\u308a\u3001Credential\u60c5\u5831\u306eJSON\u30d5\u30a1\u30a4\u30eb\u4e2d\u306b\u8a18\u8f09\u3055\u308c\u3066\u3044\u308bclient_email\u306b\n\u7de8\u96c6\u8005\u6a29\u9650\u3092\u4e0e\u3048\u305f\u3002\n\u518d\u5ea6\u5b9f\u884c\u3059\u308b\u3068\u6210\u529f\u3057\u305f\u3002\n\n\u305d\u306e\u4ed6\u30c8\u30e9\u30d6\u30eb\u30b7\u30e5\u30fc\u30c6\u30a3\u30f3\u30b0\n\nPyOpenSSL\u30d1\u30c3\u30b1\u30fc\u30b8\u306e\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306b\u5931\u6557\nPyOpenSSL \u306e\u4f9d\u5b58\u30d1\u30c3\u30b1\u30fc\u30b8\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb(cffi\u30d1\u30c3\u30b1\u30fc\u30b8)\u4e2d\u306b\u5931\u6557\u3057\u305f\u3002\n\u539f\u56e0\u306fLinux\u5074\u306e\u4f9d\u5b58\u30d1\u30c3\u30b1\u30fc\u30b8\u4e0d\u8db3\u3002\ncffi\u30d1\u30c3\u30b1\u30fc\u30b8\u306e\u30c9\u30ad\u30e5\u30e1\u30f3\u30c8\u3092\u898b\u308b\u3068\u4ee5\u4e0b\u306e\u69d8\u306a\u4e00\u6587\u304c\u3042\u308b\nhttp://cffi.readthedocs.org/en/latest/installation.html\n\non CPython, on non-Windows platforms, you also need to install libffi-dev in order to compile CFFI itself.\n\n$ sudo aptitude search libffi-dev\np   libffi-dev                                                                               - Foreign Function Interface library (development files)\n$ sudo aptitude install libffi-dev\n\npip install PyOpenSSL --upgrade\n\n\u6210\u529f\n# \u3084\u308b\u3053\u3068\nPython\u30d7\u30ed\u30b0\u30e9\u30e0\u304b\u3089Google Spreadsheet\u306b\u30a2\u30af\u30bb\u30b9\u3059\u308b\u307e\u3067\u306b\u767a\u751f\u3057\u305f\u554f\u984c\u3068\u3001\u305d\u306e\u5bfe\u7b56\u306e\u899a\u66f8\u3002\n\n\n# \u65b9\u6cd5\nGoogle Spreadsheet\u3092\u8aad\u307f\u66f8\u304d\u3059\u308b\u305f\u3081\u306ePython\u30e9\u30a4\u30d6\u30e9\u30ea\u3067\u3042\u308b`gspread`\u3092\u4f7f\u3046\u3002\nhttps://github.com/burnash/gspread\n\n\n# gspread\u306e\u4f7f\u3044\u65b9\n\u3042\u3089\u304b\u3058\u3081\u3001`testbook`\u3068\u3044\u3046\u540d\u524d\u306e\u30b9\u30d7\u30ec\u30c3\u30c9\u30b7\u30fc\u30c8\u3092Google Spreadsheet\u4e0a\u306b\u4f5c\u6210\u3057\u305f\u3002\n\n\u30a2\u30af\u30bb\u30b9\u306f\nhttp://gspread.readthedocs.org/en/latest/oauth2.html\n\u306e\u901a\u308a\u306b\u3002\n\u307b\u307c\u30b5\u30f3\u30d7\u30eb\u305d\u306e\u307e\u307e\u306e\u4ee5\u4e0b\u3092\u5b9f\u884c\u3059\u308b\u3002\n\n```python\n    import gspread\n    from oauth2client.service_account import ServiceAccountCredentials\n\n    scope = ['https://spreadsheets.google.com/feeds']\n    credentials = ServiceAccountCredentials.from_json_keyfile_name(\n        'sample-xxxxxx.json', scope)\n\n    gc = gspread.authorize(credentials)\n    wks = gc.open(\"testbook\")\n```\n\n\u8aad\u307f\u66f8\u304d\u306e\u6e96\u5099\u3068\u3057\u3066Google spreadsheet\u4e0a\u306b\u3042\u308b\u30b9\u30d7\u30ec\u30c3\u30c9\u30b7\u30fc\u30c8\u3092\u958b\u304f\u3060\u3051\u3002\n\u304c\u3001\u5931\u6557\u3057\u305f\u3002\n\u4ee5\u4e0b\u3001\u4e0a\u8a18\u3092\u52d5\u304b\u3059\u307e\u3067\u306b\u767a\u751f\u3057\u305f\u8907\u6570\u306e\u554f\u984c\u305d\u308c\u305e\u308c\u306b\u3064\u3044\u3066\u3001\u5185\u5bb9\u3068\u305d\u306e\u5bfe\u7b56\u3002\n\n\n# \u30c8\u30e9\u30d6\u30eb\u30b7\u30e5\u30fc\u30c6\u30a3\u30f3\u30b0\n## oauth2client.client.HttpAccessTokenRefreshError\n\u307e\u305a\u51fa\u305f\u30a8\u30e9\u30fc\n\n```console\nTraceback (most recent call last):\n(\u4e2d\u7565)\n    gc = gspread.authorize(credentials)\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 331, in authorize\n    client.login()\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 101, in login\n    self.auth.refresh(http)\n  File \"/usr/local/lib/python2.7/dist-packages/oauth2client/client.py\", line 659, in refresh\n    self._refresh(http.request)\n  File \"/usr/local/lib/python2.7/dist-packages/oauth2client/client.py\", line 864, in _refresh\n    self._do_refresh_request(http_request)\n  File \"/usr/local/lib/python2.7/dist-packages/oauth2client/client.py\", line 933, in _do_refresh_request\n    raise HttpAccessTokenRefreshError(error_msg, status=resp.status)\noauth2client.client.HttpAccessTokenRefreshError: invalid_grant: Invalid JWT: Token must be a short-lived token and in a reasonable timeframe\n```\n\n\u539f\u56e0\u306f\u6642\u523b\u540c\u671f\u304c\u3055\u308c\u305f\u3044\u306a\u304b\u3063\u305f\u3053\u3068(\u5b9f\u6642\u9593\u3088\u308a\u9045\u308c\u3066\u3044\u305f)\u3002\n\u6642\u523b\u3092\u540c\u671f\u5f8c\u306b\u518d\u5ea6\u5b9f\u884c\u3059\u308b\u3068\n`oauth2client.client.HttpAccessTokenRefreshError`\u306f\u51fa\u306a\u304f\u306a\u3063\u305f\u3002\n\ngoogle api - Token must be a short-lived token and in a reasonable timeframe - Stack Overflow\nhttp://stackoverflow.com/questions/36189612/token-must-be-a-short-lived-token-and-in-a-reasonable-timeframe\n\n\n\u304c\u3001\u5225\u306e\u30a8\u30e9\u30fc\u3067\u5931\u6557\u3002\n\n## requests.exceptions.SSLError\n```console\nTraceback (most recent call last):\n(\u4e2d\u7565)\n    wks = gc.open(\"testbook\")\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 145, in open\n    feed = self.get_spreadsheets_feed()\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 231, in get_spreadsheets_feed\n    r = self.session.get(url)\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py\", line 75, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/httpsession.py\", line 67, in request\n    response = func(url, data=data, headers=request_headers)\n  File \"/usr/lib/python2.7/dist-packages/requests/api.py\", line 60, in get\n    return request('get', url, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/api.py\", line 49, in request\n    return session.request(method=method, url=url, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/sessions.py\", line 457, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/sessions.py\", line 569, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/lib/python2.7/dist-packages/requests/adapters.py\", line 420, in send\n    raise SSLError(e, request=request)\nrequests.exceptions.SSLError\n```\n\npython 2.7\u7cfb\u3060\u3068\u767a\u751f\u3059\u308b\uff1fPython 3.5.1\u3067\u306f\u767a\u751f\u3057\u306a\u304b\u3063\u305f\u3002\npython 2.7\u3067\u306e\u5f53\u9762\u306e\u5bfe\u7b56\u306f\u65e7\u30d0\u30fc\u30b8\u30e7\u30f3\u306e`certifi`\u3092\u5165\u308c\u308b\u3053\u3068\u3002\n\n```\npip uninstall -y certifi && pip install certifi==2015.04.28\n```\n\nssl - SSL3_GET_SERVER_CERTIFICATE certificate verify failed on Python when requesting (only) *.google.com - Stack Overflow\nhttp://stackoverflow.com/questions/34646942/ssl3-get-server-certificate-certificate-verify-failed-on-python-when-requesting\n\n\u5143\u3005\u5165\u3063\u3066\u3044\u305f`certifi`\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u306f\n\n```console\npip list | grep certifi\ncertifi (2015.11.20.1)\n```\n\n\u518d\u5b9f\u884c\u3059\u308b\u3068\u3001`requests.exceptions.SSLError`\u306f\u51fa\u306a\u304f\u306a\u3063\u305f\u304c\u3001\u307e\u305f\u5225\u306e\u30a8\u30e9\u30fc\u304c\u767a\u751f\u3002\n\n\n## SpreadsheetNotFound\n```\nTraceback (most recent call last):\n(\u4e2d\u7565)\n    wks = gc.open(\"testbook\")\n  File \"/usr/local/lib/python2.7/dist-packages/gspread/client.py\", line 152, in open\n    raise SpreadsheetNotFound\ngspread.exceptions.SpreadsheetNotFound\n```\n\n`gspread`\u306e\u30c9\u30ad\u30e5\u30e1\u30f3\u30c8\u306b\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u4e00\u6587\u304c\u3042\u308b\u3002\n\nUsing OAuth2 for Authorization \u2014 gspread 0.3.0 documentation\nhttp://gspread.readthedocs.org/en/latest/oauth2.html\n\n>Go to Google Sheets and share your spreadsheet with an email you have in your json_key['client_email']. Otherwise you\u2019ll get a SpreadsheetNotFound exception when trying to open it.\n\n\u3053\u308c\u306e\u901a\u308a\u3001Credential\u60c5\u5831\u306eJSON\u30d5\u30a1\u30a4\u30eb\u4e2d\u306b\u8a18\u8f09\u3055\u308c\u3066\u3044\u308b`client_email`\u306b\n\u7de8\u96c6\u8005\u6a29\u9650\u3092\u4e0e\u3048\u305f\u3002\n\n\u518d\u5ea6\u5b9f\u884c\u3059\u308b\u3068\u6210\u529f\u3057\u305f\u3002\n\n\n# \u305d\u306e\u4ed6\u30c8\u30e9\u30d6\u30eb\u30b7\u30e5\u30fc\u30c6\u30a3\u30f3\u30b0\n## `PyOpenSSL`\u30d1\u30c3\u30b1\u30fc\u30b8\u306e\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u306b\u5931\u6557\nPyOpenSSL \u306e\u4f9d\u5b58\u30d1\u30c3\u30b1\u30fc\u30b8\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb(`cffi`\u30d1\u30c3\u30b1\u30fc\u30b8)\u4e2d\u306b\u5931\u6557\u3057\u305f\u3002\n\u539f\u56e0\u306fLinux\u5074\u306e\u4f9d\u5b58\u30d1\u30c3\u30b1\u30fc\u30b8\u4e0d\u8db3\u3002\n\n`cffi`\u30d1\u30c3\u30b1\u30fc\u30b8\u306e\u30c9\u30ad\u30e5\u30e1\u30f3\u30c8\u3092\u898b\u308b\u3068\u4ee5\u4e0b\u306e\u69d8\u306a\u4e00\u6587\u304c\u3042\u308b\n\nhttp://cffi.readthedocs.org/en/latest/installation.html\n\n>on CPython, on non-Windows platforms, you also need to install libffi-dev in order to compile CFFI itself.\n\n```\n$ sudo aptitude search libffi-dev\np   libffi-dev                                                                               - Foreign Function Interface library (development files)\n$ sudo aptitude install libffi-dev\n```\n\n```\npip install PyOpenSSL --upgrade\n```\n\n\u6210\u529f\n", "tags": ["Python", "GoogleSpreadSheet", "gspread"]}