{"context": "\n\ntl;dr\n\nhdf5\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u304c\u53e4\u3044\u3068Keras\u306esave_weights\u304c\u52d5\u304b\u306a\u3044\nyum\u3067hdf5-devel\u3092\u5165\u308c\u308b\u306e\u306f\u3084\u3081\u3066\u3001\u30bd\u30fc\u30b9\u30b3\u30fc\u30c9\u304b\u3089\u30b3\u30f3\u30d1\u30a4\u30eb\u3057\u3088\u3046\n\n\n\u6982\u8981\nKeras\u3067\u306f\u30e2\u30c7\u30eb\u3092\u4fdd\u5b58/\u30ed\u30fc\u30c9\u3059\u308b\u969b\u306bHDF5\u3092\u5229\u7528\u3057\u307e\u3059\u3002\u3053\u306eHDF5\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u304c\u53e4\u3044\u3068HDF5\u306e\u30a8\u30e9\u30fc\u3067\u843d\u3061\u308b\u3053\u3068\u304c\u3042\u308b\u306e\u3067\u3001\u305d\u306e\u30a8\u30e9\u30fc\u3068\u5bfe\u7b56\u3092\u66f8\u304d\u6b8b\u3057\u3066\u304a\u304d\u307e\u3059\u3002\n\n\u30a8\u30e9\u30fc\n$ python test.py \nUsing Theano backend.\nTraceback (most recent call last):\n  File \"test.py\", line 21, in <module>\n    model.save_weights('temp_keras.model', overwrite=True)\n  File \"/usr/local/lib/python2.7/site-packages/keras/engine/topology.py\", line 2282, in save_weights\n    g.attrs['weight_names'] = weight_names\n  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-7ZnOvG/h5py/h5py/_objects.c:2682)\n  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-7ZnOvG/h5py/h5py/_objects.c:2640)\n  File \"/usr/local/lib64/python2.7/site-packages/h5py/_hl/attrs.py\", line 93, in __setitem__\n    self.create(name, data=value, dtype=base.guess_dtype(value))\n  File \"/usr/local/lib64/python2.7/site-packages/h5py/_hl/attrs.py\", line 175, in create\n    space = h5s.create_simple(shape)\n  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-7ZnOvG/h5py/h5py/_objects.c:2682)\n  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-7ZnOvG/h5py/h5py/_objects.c:2640)\n  File \"h5py/h5s.pyx\", line 101, in h5py.h5s.create_simple (/tmp/pip-build-7ZnOvG/h5py/h5py/h5s.c:1533)\nValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)\n\n\n\u5bfe\u5fdc\n\n\u6700\u65b0\u7248hdf5\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n\u3053\u3053\u3067\u306f\u30012016/5/25\u73fe\u5728\u3067\u6700\u65b0\u7248\u306e1.18.17\u3092\u3001$HOME/local\u4ee5\u4e0b\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u307e\u3059\u3002\n$ wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.17.tar\n$ tar xvf hdf5-1.8.17.tar\n$ cd hdf5-1.8.17/\n$ ./configure --prefix=$HOME/local\n$ make\n$ make install\n\n\nh5py\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n\u6700\u65b0\u7248\u306ehdf5\u3092\u3082\u3068\u306b\u3001h5py\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u307e\u3059\u3002\n# \u53e4\u3044\u74b0\u5883\u306e\u524a\u9664\n$ pip uninstall h5py \n$ sudo yum remove hdf5-devel\n\n# LIBRARY_PATH\u3084INCLUDE_PATH\u306e\u8a2d\u5b9a\n$ export LIBRARY_PATH=$HOME/local/lib:$LIBRARY_PATH\n$ export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH\n$ export C_INCLUDE_PATH=$HOME/local/include:$C_INCLUDE_PATH\n$ export CPLUS_INCLUDE_PATH=$HOME/local/include:$CPLUS_INCLUDE_PATH\n\n# h5py\u306e\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n$ HDF5_DIR=$HOME/local/bin\n$ pip install h5py\n\nLIBRARY_PATH\u3084INCLUDE_PATH\u307e\u308f\u308a\u304c\u8a2d\u5b9a\u3067\u304d\u3066\u3044\u306a\u3044\u3068\u3001\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u304c\u8868\u793a\u3055\u308c\u308b\u306e\u3067\u6ce8\u610f\u3067\u3059\u3002\n[...]\n    collect2: error: ld returned 1 exit status\n    error: command 'gcc' failed with exit status 1\n\n[...]\n    /tmp/pip-build-CC4cFF/h5py/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory\n     #include \"hdf5.h\"\n                      ^\n    compilation terminated.\n    error: command 'gcc' failed with exit status 1\n\n\nh5py\u3067\u4f7f\u7528\u3057\u3066\u3044\u308bhdf5\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u78ba\u8a8d\n\u3061\u3083\u3093\u3068\u81ea\u5206\u3067\u30b3\u30f3\u30d1\u30a4\u30eb\u3057\u305f\u6700\u65b0\u7248\u306ehdf5\u304c\u4f7f\u7528\u3055\u308c\u3066\u3044\u308b\u304b\u78ba\u8a8d\u3057\u307e\u3059\u3002\nIn [1]: import h5py\n\nIn [2]: print(h5py.version.info)\nSummary of the h5py configuration\n---------------------------------\n\nh5py    2.6.0\nHDF5    1.8.17\nPython  3.4.4 (default, May 19 2016, 04:58:42)\n[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]\nsys.platform    linux\nsys.maxsize     9223372036854775807\nnumpy   1.11.0\n\n\n\u30c6\u30b9\u30c8\n\u305d\u308c\u3067\u306fsave_weights\u304c\u6b63\u5e38\u306b\u52d5\u4f5c\u3059\u308b\u304b\u3092\u3001\u9069\u5f53\u306amodel\u3092\u4f5c\u3063\u3066\u78ba\u304b\u3081\u3066\u307f\u307e\u3059\u3002\u4ee5\u4e0b\u306e\u30b3\u30fc\u30c9\u3092\u5b9f\u884c\u3057\u3066keras.h5\u304c\u6b63\u5e38\u306b\u51fa\u529b\u3055\u308c\u308c\u3070\u5b8c\u4e86\u3067\u3059\u3002\n# test.py\nfrom keras.models import Sequential\nfrom keras.layers.core import Dense, Dropout, Activation\n\nmodel = Sequential()\nmodel.add(Dense(512, input_shape=(784,)))\nmodel.add(Activation('relu'))\nmodel.add(Dropout(0.2))\nmodel.add(Dense(512))\nmodel.add(Activation('relu'))\nmodel.add(Dropout(0.2))\nmodel.add(Dense(10))\nmodel.add(Activation('softmax'))\n\nmodel.compile(loss='categorical_crossentropy', optimizer='rmsprop')\nmodel.save_weights('keras.h5')\n\n\n\u53c2\u8003\n\n\nFAQ - Keras Documentation\n\nKeras\u306b\u304a\u3051\u308b\u30e2\u30c7\u30eb\u306e\u4fdd\u5b58\u65b9\u6cd5\n\n\n\nBug Reports & Contributions \u2014 h5py 2.6.0 documentation\n\nh5py\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u306e\u78ba\u8a8d\u65b9\u6cd5\n\n\n\n \n### tl;dr\n\n- hdf5\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u304c\u53e4\u3044\u3068Keras\u306esave_weights\u304c\u52d5\u304b\u306a\u3044\n- yum\u3067hdf5-devel\u3092\u5165\u308c\u308b\u306e\u306f\u3084\u3081\u3066\u3001\u30bd\u30fc\u30b9\u30b3\u30fc\u30c9\u304b\u3089\u30b3\u30f3\u30d1\u30a4\u30eb\u3057\u3088\u3046\n\n### \u6982\u8981\n\nKeras\u3067\u306f\u30e2\u30c7\u30eb\u3092\u4fdd\u5b58/\u30ed\u30fc\u30c9\u3059\u308b\u969b\u306b[HDF5](https://www.hdfgroup.org/HDF5/)\u3092\u5229\u7528\u3057\u307e\u3059\u3002\u3053\u306eHDF5\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u304c\u53e4\u3044\u3068HDF5\u306e\u30a8\u30e9\u30fc\u3067\u843d\u3061\u308b\u3053\u3068\u304c\u3042\u308b\u306e\u3067\u3001\u305d\u306e\u30a8\u30e9\u30fc\u3068\u5bfe\u7b56\u3092\u66f8\u304d\u6b8b\u3057\u3066\u304a\u304d\u307e\u3059\u3002\n \n### \u30a8\u30e9\u30fc\n\n \n ```\n$ python test.py \nUsing Theano backend.\nTraceback (most recent call last):\n  File \"test.py\", line 21, in <module>\n    model.save_weights('temp_keras.model', overwrite=True)\n  File \"/usr/local/lib/python2.7/site-packages/keras/engine/topology.py\", line 2282, in save_weights\n    g.attrs['weight_names'] = weight_names\n  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-7ZnOvG/h5py/h5py/_objects.c:2682)\n  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-7ZnOvG/h5py/h5py/_objects.c:2640)\n  File \"/usr/local/lib64/python2.7/site-packages/h5py/_hl/attrs.py\", line 93, in __setitem__\n    self.create(name, data=value, dtype=base.guess_dtype(value))\n  File \"/usr/local/lib64/python2.7/site-packages/h5py/_hl/attrs.py\", line 175, in create\n    space = h5s.create_simple(shape)\n  File \"h5py/_objects.pyx\", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-7ZnOvG/h5py/h5py/_objects.c:2682)\n  File \"h5py/_objects.pyx\", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-7ZnOvG/h5py/h5py/_objects.c:2640)\n  File \"h5py/h5s.pyx\", line 101, in h5py.h5s.create_simple (/tmp/pip-build-7ZnOvG/h5py/h5py/h5s.c:1533)\nValueError: Zero sized dimension for non-unlimited dimension (Zero sized dimension for non-unlimited dimension)\n ```\n \n### \u5bfe\u5fdc\n \n#### \u6700\u65b0\u7248hdf5\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n\n\u3053\u3053\u3067\u306f\u30012016/5/25\u73fe\u5728\u3067\u6700\u65b0\u7248\u306e1.18.17\u3092\u3001`$HOME/local`\u4ee5\u4e0b\u306b\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u3066\u3044\u307e\u3059\u3002\n \n```sh\n$ wget http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.17.tar\n$ tar xvf hdf5-1.8.17.tar\n$ cd hdf5-1.8.17/\n$ ./configure --prefix=$HOME/local\n$ make\n$ make install\n```\n\n\n#### h5py\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n\n\u6700\u65b0\u7248\u306ehdf5\u3092\u3082\u3068\u306b\u3001h5py\u3092\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3057\u307e\u3059\u3002\n\n```sh\n# \u53e4\u3044\u74b0\u5883\u306e\u524a\u9664\n$ pip uninstall h5py \n$ sudo yum remove hdf5-devel\n\n# LIBRARY_PATH\u3084INCLUDE_PATH\u306e\u8a2d\u5b9a\n$ export LIBRARY_PATH=$HOME/local/lib:$LIBRARY_PATH\n$ export LD_LIBRARY_PATH=$HOME/local/lib:$LD_LIBRARY_PATH\n$ export C_INCLUDE_PATH=$HOME/local/include:$C_INCLUDE_PATH\n$ export CPLUS_INCLUDE_PATH=$HOME/local/include:$CPLUS_INCLUDE_PATH\n\n# h5py\u306e\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\n$ HDF5_DIR=$HOME/local/bin\n$ pip install h5py\n```\n\nLIBRARY_PATH\u3084INCLUDE_PATH\u307e\u308f\u308a\u304c\u8a2d\u5b9a\u3067\u304d\u3066\u3044\u306a\u3044\u3068\u3001\u4ee5\u4e0b\u306e\u3088\u3046\u306a\u30a8\u30e9\u30fc\u304c\u8868\u793a\u3055\u308c\u308b\u306e\u3067\u6ce8\u610f\u3067\u3059\u3002\n\n```\n[...]\n    collect2: error: ld returned 1 exit status\n    error: command 'gcc' failed with exit status 1\n```\n\n```\n[...]\n    /tmp/pip-build-CC4cFF/h5py/h5py/api_compat.h:27:18: fatal error: hdf5.h: No such file or directory\n     #include \"hdf5.h\"\n                      ^\n    compilation terminated.\n    error: command 'gcc' failed with exit status 1\n```\n\n#### h5py\u3067\u4f7f\u7528\u3057\u3066\u3044\u308bhdf5\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u78ba\u8a8d\n\n\u3061\u3083\u3093\u3068\u81ea\u5206\u3067\u30b3\u30f3\u30d1\u30a4\u30eb\u3057\u305f\u6700\u65b0\u7248\u306ehdf5\u304c\u4f7f\u7528\u3055\u308c\u3066\u3044\u308b\u304b\u78ba\u8a8d\u3057\u307e\u3059\u3002\n\n```py\nIn [1]: import h5py\n\nIn [2]: print(h5py.version.info)\nSummary of the h5py configuration\n---------------------------------\n\nh5py    2.6.0\nHDF5    1.8.17\nPython  3.4.4 (default, May 19 2016, 04:58:42)\n[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]\nsys.platform    linux\nsys.maxsize     9223372036854775807\nnumpy   1.11.0\n```\n\n### \u30c6\u30b9\u30c8\n\n\u305d\u308c\u3067\u306f`save_weights`\u304c\u6b63\u5e38\u306b\u52d5\u4f5c\u3059\u308b\u304b\u3092\u3001\u9069\u5f53\u306amodel\u3092\u4f5c\u3063\u3066\u78ba\u304b\u3081\u3066\u307f\u307e\u3059\u3002\u4ee5\u4e0b\u306e\u30b3\u30fc\u30c9\u3092\u5b9f\u884c\u3057\u3066keras.h5\u304c\u6b63\u5e38\u306b\u51fa\u529b\u3055\u308c\u308c\u3070\u5b8c\u4e86\u3067\u3059\u3002\n\n```py\n# test.py\nfrom keras.models import Sequential\nfrom keras.layers.core import Dense, Dropout, Activation\n\nmodel = Sequential()\nmodel.add(Dense(512, input_shape=(784,)))\nmodel.add(Activation('relu'))\nmodel.add(Dropout(0.2))\nmodel.add(Dense(512))\nmodel.add(Activation('relu'))\nmodel.add(Dropout(0.2))\nmodel.add(Dense(10))\nmodel.add(Activation('softmax'))\n\nmodel.compile(loss='categorical_crossentropy', optimizer='rmsprop')\nmodel.save_weights('keras.h5')\n```\n\n\n### \u53c2\u8003\n\n- [FAQ - Keras Documentation](http://keras.io/getting-started/faq/#how-can-i-save-a-keras-model)\n\t- Keras\u306b\u304a\u3051\u308b\u30e2\u30c7\u30eb\u306e\u4fdd\u5b58\u65b9\u6cd5\n- [Bug Reports & Contributions \u2014 h5py 2.6.0 documentation](http://docs.h5py.org/en/latest/contributing.html)\n\t- h5py\u306e\u30d0\u30fc\u30b8\u30e7\u30f3\u306e\u78ba\u8a8d\u65b9\u6cd5\n", "tags": ["Python", "Keras"]}