{"context": "\npython\nfrom selenium.webdriver import Firefox\ndriver = Firefox()\ndriver.get('http://example.com')\n\n\n\u3057\u305f\u6642\u306b\u3001\nCan't load the profile. \u3068\u3044\u3046\u30a8\u30e9\u30fc\u304c\u51fa\u308b\u5bfe\u5fdc\u3002mac\u3002\nFirefox 47 \u304b\u3089\u5165\u3063\u3066\u308b\u30de\u30ea\u30aa\u30cd\u30c3\u30c8 marionette \u3068\u3044\u3046\u74b0\u5883\u69cb\u6210\u30b7\u30b9\u30c6\u30e0(?) \u306b\u3001Selenium \u304c\u5bfe\u5fdc\u3067\u304d\u3066\u3044\u306a\u3044?\ngeckodriver \u3092 brew \u3067\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3059\u308b\u3002\n\ncommand\n$ brew install geckodriver\n$ pip install -U selenium\n\n\n\npython\nfirefox_capabilities = DesiredCapabilities.FIREFOX\nfirefox_capabilities['marionette'] = True\n\ndriver = webdriver.Firefox(capabilities=firefox_capabilities)\ndriver.get('http://example.com')\n\n\n\u3053\u308c\u3067OK\n\u53c2\u8003: Can't open browser with Selenium after Firefox update - Stack Overflow\n\n\u8ffd\u8a18\n\u305d\u306e\u5f8c\u3001\nselenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. \n\nException AttributeError: \"'Service' object has no attribute 'process'\" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x109a96690>> ignored\n\n\u3053\u308c\u304c\u51fa\u305f\u3089\n\npython\nimport os\nif \"/usr/local/bin\" not in os.environ['PATH']:\n    os.environ['PATH'] += os.pathsep + \"/usr/local/bin\"\n\n\n```python:python\nfrom selenium.webdriver import Firefox\ndriver = Firefox()\ndriver.get('http://example.com')\n```\n\n\u3057\u305f\u6642\u306b\u3001\n\n`Can't load the profile.` \u3068\u3044\u3046\u30a8\u30e9\u30fc\u304c\u51fa\u308b\u5bfe\u5fdc\u3002mac\u3002\n\nFirefox 47 \u304b\u3089\u5165\u3063\u3066\u308b\u30de\u30ea\u30aa\u30cd\u30c3\u30c8 marionette \u3068\u3044\u3046\u74b0\u5883\u69cb\u6210\u30b7\u30b9\u30c6\u30e0(?) \u306b\u3001Selenium \u304c\u5bfe\u5fdc\u3067\u304d\u3066\u3044\u306a\u3044?\n\ngeckodriver \u3092 brew \u3067\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3059\u308b\u3002\n\n```bash:command\n$ brew install geckodriver\n$ pip install -U selenium\n```\n\n```python:python\nfirefox_capabilities = DesiredCapabilities.FIREFOX\nfirefox_capabilities['marionette'] = True\n\ndriver = webdriver.Firefox(capabilities=firefox_capabilities)\ndriver.get('http://example.com')\n```\n\n\u3053\u308c\u3067OK\n\n\u53c2\u8003: [Can't open browser with Selenium after Firefox update - Stack Overflow](http://stackoverflow.com/questions/37761668/cant-open-browser-with-selenium-after-firefox-update)\n\n## \u8ffd\u8a18\n\n\u305d\u306e\u5f8c\u3001\n\n```\nselenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH. \n\nException AttributeError: \"'Service' object has no attribute 'process'\" in <bound method Service.__del__ of <selenium.webdriver.firefox.service.Service object at 0x109a96690>> ignored\n```\n\u3053\u308c\u304c\u51fa\u305f\u3089\n\n```python:python\nimport os\nif \"/usr/local/bin\" not in os.environ['PATH']:\n    os.environ['PATH'] += os.pathsep + \"/usr/local/bin\"\n```\n", "tags": ["Python", "Selenium", "firefox"]}